core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('stock.urls')),
    path('', include('django.contrib.auth.urls')),
    path("select2/", include("django_select2.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

stock/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='/'),
    path('sign-up', views.sign_up, name='sign-up'),

    path('categories', views.categories, name='categories'),
    path('create-categorie', views.create_category, name='create-categorie'),
    path('update-categorie/<int:id>', views.update_category, name='update-categorie'),
    path('delete-categorie/<int:id>', views.delete_category, name='delete-categorie'),

    path('produits', views.produits, name='produits'),
    path('create-produit', views.create_produit, name='create-produit'),
    path('update-produit/<int:id>', views.update_produit, name='update-produit'),
    path('delete-produit/<int:id>', views.delete_produit, name='delete-produit'),

    path('commandeconsuls', views.commandeconsuls, name='commandeconsuls'),
    path('create-commandeconsul', views.create_commandeconsul, name='create-commandeconsul'),
    path('update-commandeconsul/<int:id>', views.update_commandeconsul, name='update-commandeconsul'),
    path('delete-commandeconsul/<int:id>', views.delete_commandeconsul, name='delete-commandeconsul'),

    path('lcommandes', views.listCommande, name='lcommandes'),
    path('create-lcommandes', views.create_listcommande, name='create-lcommandes'),
    path('update-produitcommande/<int:id>', views.update_lignecommande, name='update-produitcommande'),
    path('delete-produitcommande/<int:id>', views.delete_lignecommande, name='delete-produitcommande'),

    path('livraisons', views.listLivraison, name='livraisons'),
    path('create-llivraisons', views.create_listlivraison, name='create-llivraisons'),
    path('update-llivraisons/<int:id>', views.update_listlivraison, name='update-llivraisons'),
    path('delete-llivraisons/<int:id>', views.delete_listlivraison, name='delete-llivraisons'),
    path('validate-llivraisons/<int:id>', views.validate_listlivraison, name='validate-llivraisons'),
    path('ajax/load_cmd/', views.load_fourniture_cmd, name='ajax_load_fcmd'),

    path('tarifications', views.tarifications, name='tarifications'),
    path('create-tarification', views.create_tarification, name='create-tarification'),
    path('update-tarification/<int:id>', views.update_tarification, name='update-tarification'),
    path('delete-tarification/<int:id>', views.delete_tarification, name='delete-tarification'),

    path('ventes', views.listVente, name='ventes'),
    path('create-vente', views.create_listventes, name='create-vente'),
    path('ajax_load_tarif/', views.load_tarif_produit, name='ajax_load_tarif'),
    path('ajax_load_qte/', views.load_qte_dispo, name='ajax_load_qte'),
    path('delete-vente/<int:id>', views.delete_listvente, name='delete-vente'),
    path('validate-vente/<int:id>', views.validate_listvente, name='validate-vente'),
    path('pdf_view/', views.ViewPDF_Facture.as_view(), name='pdf_view'),

    path('situations', views.situationStock, name='situations'),
    path('etat_vente', views.etatstockvente, name='etat_vente'),
    path('etat_situationstock', views.etatstockproduitperiode, name='etat_situationstock'),
]

stock/models.py
from django.contrib.auth.models import User
from django.db import models


class Categorie(models.Model):
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT)
    codeC = models.CharField(max_length=10, blank=False, null=False, unique=True)
    nomC = models.CharField(max_length=30, blank=False, null=False, unique=True)
    descriptC = models.CharField(max_length=80)
    disponibleC = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nomC


class Produit(models.Model):
    P_U = 'UNITE'
    P_C_10 = 'CARTON 10'
    P_C_20 = 'CARTON 20'
    MES_P = [
        (P_U, 'UNITE'),
        (P_C_10, 'CARTON 10'),
        (P_C_20, 'CARTON 20'),
    ]
    auteurP = models.ForeignKey(User, on_delete=models.PROTECT)
    categorie = models.ForeignKey(Categorie, on_delete=models.PROTECT,)
    codeP = models.CharField(max_length=10, blank=False, null=False, unique=True)
    nomP = models.CharField(max_length=30, blank=False, null=False, unique=True)
    descriptP = models.CharField(max_length=80)
    disponibleP = models.BooleanField(default=True)
    quantiteMinP = models.PositiveIntegerField()
    mesureP = models.CharField(max_length=30, choices=MES_P, default='', blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeP + " " + self.nomP + " " + self.mesureP


class CommandeConsultant(models.Model):
    EN_COURS = 'EN COURS'
    TRAITEE = 'TRAITEE'
    NON_DISPO = 'PDT RUPTURE STOCK'
    CHOIX = [
        (EN_COURS, 'EN COURS'),
        (TRAITEE, 'TRAITEE'),
        (NON_DISPO, 'PDT RUPTURE STOCK'),
    ]
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT, related_name="autheur_consul")
    auteurT = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name="autheur_admin")
    codeC = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateC = models.DateField()
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    disponible = models.BooleanField(default=True)
    statut = models.CharField(max_length=30, choices=CHOIX, default=EN_COURS)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeC

class Commande(models.Model):
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT)
    codeC = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateC = models.DateField()
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeC


class LigneCommande(models.Model):
    EN_COURS = 'EN COURS'
    LIVREE = 'LIVREE'
    CHOIX = [
        (EN_COURS, 'EN COURS'),
        (LIVREE, 'LIVREE'),
    ]
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT)
    commande = models.ForeignKey(Commande, on_delete=models.PROTECT)
    statut = models.CharField(max_length=15, choices=CHOIX, default=EN_COURS)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    disponible = models.BooleanField(default=True)
    date_modified = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.commande.codeC + " " + self.produit.nomP)


class Livraison(models.Model):
    auteurL = models.ForeignKey(User, on_delete=models.PROTECT)
    codeL = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateL = models.DateField()
    fournisseur = models.CharField(max_length=100, blank=False, null=False, unique=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeL


class LigneLivraison(models.Model):
    NON_VA = 'NON-VA'
    VA = 'VA'
    CHOIX = [
        (NON_VA, 'NON-VA'),
        (VA, 'VA'),
    ]
    auteurL = models.ForeignKey(User, on_delete=models.PROTECT)
    livraison = models.ForeignKey(Livraison, on_delete=models.PROTECT)
    commande = models.ForeignKey(LigneCommande, on_delete=models.PROTECT)
    statut = models.CharField(max_length=15, choices=CHOIX, default=NON_VA)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    prixHt = models.FloatField()
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.livraison)


class Tarification(models.Model):
    ACTUELLE = 'ACTUELLE'
    OBSOLETE = 'OBSOLETE'
    CHOIX = [
        (ACTUELLE, 'ACTUELLE'),
        (OBSOLETE, 'OBSOLETE'),
    ]
    NON_VA = 'NON-VA'
    VA = 'VA'
    CHOIX_S = [
        (NON_VA, 'NON-VA'),
        (VA, 'VA'),
    ]
    auteurT = models.ForeignKey(User, on_delete=models.PROTECT)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    prix = models.FloatField()
    dateD = models.DateField()
    dateF = models.DateField(null=True, blank=True)
    vigeur = models.CharField(max_length=15, choices=CHOIX, default=ACTUELLE)
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.prix)


class Vente(models.Model):
    auteurV = models.ForeignKey(User, on_delete=models.PROTECT)
    codeV = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateV = models.DateField()
    client = models.CharField(max_length=100, blank=False, null=False, unique=True)
    remise = models.IntegerField(default=0)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeV


class LigneVente(models.Model):
    NON_VA = 'NON-VA'
    VA = 'VA'
    CHOIX = [
        (NON_VA, 'NON-VA'),
        (VA, 'VA'),
    ]
    auteurL = models.ForeignKey(User, on_delete=models.PROTECT)
    vente = models.ForeignKey(Vente, on_delete=models.PROTECT)
    tarification = models.ForeignKey(Tarification, on_delete=models.PROTECT)
    statut = models.CharField(max_length=15, choices=CHOIX, default=NON_VA)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.vente)


class Mouvement(models.Model):
    auteurM = models.ForeignKey(User, on_delete=models.PROTECT)
    dateM = models.DateField()
    llivraison = models.ForeignKey(LigneLivraison, on_delete=models.PROTECT, null=True)
    sortie = models.ForeignKey(LigneVente, on_delete=models.PROTECT, null=True)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    IN = 'IN'
    OUT = 'OUT'
    CHOIX_MOUVEMENT = [
        (IN, 'IN'),
        (OUT, 'OUT'),
    ]
    type = models.CharField(
        max_length=8,
        choices=CHOIX_MOUVEMENT,
        default="",
    )
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.produit

stock/templates/produit/produit_form.html
{% extends '../base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">{{ titre }} - Produit</h2>
    </div>
</div>

{% if messages %}
<div class="container">
        <div class="col-md-4" style="margin-left: 955px">
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{message}}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
</div>
{% endif %}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Formulaire Produit

                <div class="pull-right">
                    <div class="btn-group">
                        <a href="/produits" class="btn btn-default btn-xs">
                            Liste Produits
                        </a>
                    </div>
                </div>
            </div>
            <form role="form" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="panel-body">
                        <div class="form-row">
                            <div class="form-group col-md-2">
                                {{ form.codeP|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.nomP|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.descriptP|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-2">
                                {{ form.quantiteMinP|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.mesureP|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-4">
                                {{ form.categorie|as_crispy_field }}
                            </div>
                        </div>
                </div>
                <div class="panel-footer">
                    <div class="text-right">
                            <button type="reset" class="btn btn-sm btn-warning">Annuler</button>
                            <button type="submit" class="btn btn-sm btn-info">Enregistrer</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function () {
        // Apply Select2 styling to the categorie field
        $('#id_categorie').select2({

        });
    });
</script>
{% endblock %}

stock/templates/produit/produits.html
{% extends '../base.html' %}

{% block content %}
{% load static %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Produit</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>

{% if messages %}
<div class="container">
        <div class="col-md-4" style="margin-left: 955px">
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{message}}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
</div>
{% endif %}

<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Liste Produit

                <div class="pull-right">
                    <div class="btn-group">
                        <a href="/create-produit" class="btn btn-primary btn-xs">
                            <i class="fa fa-plus fa-fw"></i>
                            Ajouter
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                {% if produits|length > 0 %}
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-produit">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Code</th>
                            <th>Nom</th>
                            <th>Description</th>
                            <th>Quantité Min</th>
                            <th>Mesure</th>
                            <th>Catégorie</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for produit in produits %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ produit.codeP }}</td>
                                <td>{{ produit.nomP }}</td>
                                <td>{{ produit.descriptP }}</td>
                                <td>{{ produit.quantiteMinP }}</td>
                                <td>{{ produit.mesureP }}</td>
                                <td>{{ produit.categorie }}</td>
                                <td class="text-center">
                                    <div>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-cog"></i></span>
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu pull-right" role="menu">
                                                <li><a href="{% url 'update-produit' produit.id %}"> <i class="fa fa-edit fa-fw"></i> Modifier</a>
                                                </li>
                                                <li><a href="{% url 'delete-produit' produit.id %}" onclick="return confirm('Voulez vous réelement supprimer : {{ produit.nomP }} ?')"> <i class="fa fa-trash fa-fw"></i> Supprimer</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            </tr>

                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                    <p>Aucun enregistrement disponible :-)</p>
                {% endif %}


            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>


{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#dataTables-produit').DataTable({
            language: {
                url: "{% static 'stock/js/french.json' %}"
            },
            /*"autoWidth": false,
            columns: [
                    { "width": "5%" },
                    { "width": "10%" },
                    { "width": "15%" },
                    { "width": "30%" },
                    {"width": "5%"}
            ],*/
            "columnDefs": [{
                "targets": 4,
                "orderable": false
            }],
        });
    });
</script>
{% endblock %}