core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('stock.urls')),
    path('', include('django.contrib.auth.urls')),
    path("select2/", include("django_select2.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

stock/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='/'),
    path('sign-up', views.sign_up, name='sign-up'),

    path('categories', views.categories, name='categories'),
    path('create-categorie', views.create_category, name='create-categorie'),
    path('update-categorie/<int:id>', views.update_category, name='update-categorie'),
    path('delete-categorie/<int:id>', views.delete_category, name='delete-categorie'),

    path('produits', views.produits, name='produits'),
    path('create-produit', views.create_produit, name='create-produit'),
    path('update-produit/<int:id>', views.update_produit, name='update-produit'),
    path('delete-produit/<int:id>', views.delete_produit, name='delete-produit'),

    path('commandeconsuls', views.commandeconsuls, name='commandeconsuls'),
    path('create-commandeconsul', views.create_commandeconsul, name='create-commandeconsul'),
    path('update-commandeconsul/<int:id>', views.update_commandeconsul, name='update-commandeconsul'),
    path('delete-commandeconsul/<int:id>', views.delete_commandeconsul, name='delete-commandeconsul'),

    path('lcommandes', views.listCommande, name='lcommandes'),
    path('create-lcommandes', views.create_listcommande, name='create-lcommandes'),
    path('update-produitcommande/<int:id>', views.update_lignecommande, name='update-produitcommande'),
    path('delete-produitcommande/<int:id>', views.delete_lignecommande, name='delete-produitcommande'),

    path('livraisons', views.listLivraison, name='livraisons'),
    path('create-llivraisons', views.create_listlivraison, name='create-llivraisons'),
    path('update-llivraisons/<int:id>', views.update_listlivraison, name='update-llivraisons'),
    path('delete-llivraisons/<int:id>', views.delete_listlivraison, name='delete-llivraisons'),
    path('validate-llivraisons/<int:id>', views.validate_listlivraison, name='validate-llivraisons'),
    path('ajax/load_cmd/', views.load_fourniture_cmd, name='ajax_load_fcmd'),

    path('tarifications', views.tarifications, name='tarifications'),
    path('create-tarification', views.create_tarification, name='create-tarification'),
    path('update-tarification/<int:id>', views.update_tarification, name='update-tarification'),
    path('delete-tarification/<int:id>', views.delete_tarification, name='delete-tarification'),

    path('ventes', views.listVente, name='ventes'),
    path('create-vente', views.create_listventes, name='create-vente'),
    path('ajax_load_tarif/', views.load_tarif_produit, name='ajax_load_tarif'),
    path('ajax_load_qte/', views.load_qte_dispo, name='ajax_load_qte'),
    path('delete-vente/<int:id>', views.delete_listvente, name='delete-vente'),
    path('validate-vente/<int:id>', views.validate_listvente, name='validate-vente'),
    path('pdf_view/', views.ViewPDF_Facture.as_view(), name='pdf_view'),

    path('situations', views.situationStock, name='situations'),
    path('etat_vente', views.etatstockvente, name='etat_vente'),
    path('etat_situationstock', views.etatstockproduitperiode, name='etat_situationstock'),
]

stock/models.py
from django.contrib.auth.models import User
from django.db import models


class Categorie(models.Model):
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT)
    codeC = models.CharField(max_length=10, blank=False, null=False, unique=True)
    nomC = models.CharField(max_length=30, blank=False, null=False, unique=True)
    descriptC = models.CharField(max_length=80)
    disponibleC = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nomC


class Produit(models.Model):
    P_U = 'UNITE'
    P_C_10 = 'CARTON 10'
    P_C_20 = 'CARTON 20'
    MES_P = [
        (P_U, 'UNITE'),
        (P_C_10, 'CARTON 10'),
        (P_C_20, 'CARTON 20'),
    ]
    auteurP = models.ForeignKey(User, on_delete=models.PROTECT)
    categorie = models.ForeignKey(Categorie, on_delete=models.PROTECT,)
    codeP = models.CharField(max_length=10, blank=False, null=False, unique=True)
    nomP = models.CharField(max_length=30, blank=False, null=False, unique=True)
    descriptP = models.CharField(max_length=80)
    disponibleP = models.BooleanField(default=True)
    quantiteMinP = models.PositiveIntegerField()
    mesureP = models.CharField(max_length=30, choices=MES_P, default='', blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeP + " " + self.nomP + " " + self.mesureP


class CommandeConsultant(models.Model):
    EN_COURS = 'EN COURS'
    TRAITEE = 'TRAITEE'
    NON_DISPO = 'PDT RUPTURE STOCK'
    CHOIX = [
        (EN_COURS, 'EN COURS'),
        (TRAITEE, 'TRAITEE'),
        (NON_DISPO, 'PDT RUPTURE STOCK'),
    ]
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT, related_name="autheur_consul")
    auteurT = models.ForeignKey(User, on_delete=models.PROTECT, null=True, related_name="autheur_admin")
    codeC = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateC = models.DateField()
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    disponible = models.BooleanField(default=True)
    statut = models.CharField(max_length=30, choices=CHOIX, default=EN_COURS)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeC

class Commande(models.Model):
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT)
    codeC = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateC = models.DateField()
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeC


class LigneCommande(models.Model):
    EN_COURS = 'EN COURS'
    LIVREE = 'LIVREE'
    CHOIX = [
        (EN_COURS, 'EN COURS'),
        (LIVREE, 'LIVREE'),
    ]
    auteurC = models.ForeignKey(User, on_delete=models.PROTECT)
    commande = models.ForeignKey(Commande, on_delete=models.PROTECT)
    statut = models.CharField(max_length=15, choices=CHOIX, default=EN_COURS)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    disponible = models.BooleanField(default=True)
    date_modified = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.commande.codeC + " " + self.produit.nomP)


class Livraison(models.Model):
    auteurL = models.ForeignKey(User, on_delete=models.PROTECT)
    codeL = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateL = models.DateField()
    fournisseur = models.CharField(max_length=100, blank=False, null=False, unique=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeL


class LigneLivraison(models.Model):
    NON_VA = 'NON-VA'
    VA = 'VA'
    CHOIX = [
        (NON_VA, 'NON-VA'),
        (VA, 'VA'),
    ]
    auteurL = models.ForeignKey(User, on_delete=models.PROTECT)
    livraison = models.ForeignKey(Livraison, on_delete=models.PROTECT)
    commande = models.ForeignKey(LigneCommande, on_delete=models.PROTECT)
    statut = models.CharField(max_length=15, choices=CHOIX, default=NON_VA)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    prixHt = models.FloatField()
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.livraison)


class Tarification(models.Model):
    ACTUELLE = 'ACTUELLE'
    OBSOLETE = 'OBSOLETE'
    CHOIX = [
        (ACTUELLE, 'ACTUELLE'),
        (OBSOLETE, 'OBSOLETE'),
    ]
    NON_VA = 'NON-VA'
    VA = 'VA'
    CHOIX_S = [
        (NON_VA, 'NON-VA'),
        (VA, 'VA'),
    ]
    auteurT = models.ForeignKey(User, on_delete=models.PROTECT)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    prix = models.FloatField()
    dateD = models.DateField()
    dateF = models.DateField(null=True, blank=True)
    vigeur = models.CharField(max_length=15, choices=CHOIX, default=ACTUELLE)
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.prix)


class Vente(models.Model):
    auteurV = models.ForeignKey(User, on_delete=models.PROTECT)
    codeV = models.CharField(max_length=100, blank=False, null=False, unique=True)
    dateV = models.DateField()
    client = models.CharField(max_length=100, blank=False, null=False, unique=True)
    remise = models.IntegerField(default=0)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.codeV


class LigneVente(models.Model):
    NON_VA = 'NON-VA'
    VA = 'VA'
    CHOIX = [
        (NON_VA, 'NON-VA'),
        (VA, 'VA'),
    ]
    auteurL = models.ForeignKey(User, on_delete=models.PROTECT)
    vente = models.ForeignKey(Vente, on_delete=models.PROTECT)
    tarification = models.ForeignKey(Tarification, on_delete=models.PROTECT)
    statut = models.CharField(max_length=15, choices=CHOIX, default=NON_VA)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.vente)


class Mouvement(models.Model):
    auteurM = models.ForeignKey(User, on_delete=models.PROTECT)
    dateM = models.DateField()
    llivraison = models.ForeignKey(LigneLivraison, on_delete=models.PROTECT, null=True)
    sortie = models.ForeignKey(LigneVente, on_delete=models.PROTECT, null=True)
    produit = models.ForeignKey(Produit, on_delete=models.PROTECT)
    qte = models.IntegerField()
    IN = 'IN'
    OUT = 'OUT'
    CHOIX_MOUVEMENT = [
        (IN, 'IN'),
        (OUT, 'OUT'),
    ]
    type = models.CharField(
        max_length=8,
        choices=CHOIX_MOUVEMENT,
        default="",
    )
    disponible = models.BooleanField(default=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.produit

stock/templates/produitVente/produit_cmd.html
<option value="">---------</option>
{% for f in f_cmd %}
<option value="{{ f.id }}">{{ f.nomP }}</option>
{% endfor %}

stock/templates/produitVente/produit_tarif.html
<option value="">---------</option>
{% for t in p_tarif %}
<option value="{{ t.id }}">{{ t.prix }}</option>
{% endfor %}

stock/templates/produitVente/produitvente.html
{% extends '../base.html' %}

{% block content %}
{% load static %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Vente de Produit</h2>
    </div>
    <!-- /.col-lg-12 -->
</div>

{% if messages %}
<div class="container">
        <div class="col-md-4" style="margin-left: 955px">
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{message}}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
</div>
{% endif %}

<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Liste Vente de Produit

                <div class="pull-right">
                    <div class="btn-group">
                        <a href="/create-vente" class="btn btn-primary btn-xs">
                            <i class="fa fa-plus fa-fw"></i>
                            Ajouter
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                {% if ventes|length > 0 %}
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-produitvente">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Client</th>
                            <th>Date Vente</th>
                            <th>Code Vente</th>
                            <th>Produit</th>
                            <th>Quantité</th>
                            <th>Prix</th>
                            <th>Total HT</th>
                            <th>Statut</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for vente in ventes %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ vente.client }}</td>
                                <td>{{ vente.dateV }}</td>
                                <td>{{ vente.codeV }}</td>
                                <td>{{ vente.produit }}</td>
                                <td>{{ vente.qte }}</td>
                                <td>{{ vente.prix }}</td>
                                <td>{{ vente.totalht }}</td>
                                <!--<td>
                                    <i class="fas fa-file-pdf"></i>
                                    <form method="GET" autocomplete="off" class="form-inline"
                                          action="{% url 'pdf_view' %}">
                                        {% csrf_token %}
                                        <input type='hidden' class="form-control"
                                               value="{{ vente.id }}" id="id_vente" name="id_vente"/>
                                        <input type="submit" class="link-dark mb-2" value="Export PDF">
                                    </form>
                                </td>-->
                                <td>{{ vente.statut }}</td>
                                <td class="text-center">
                                    <div>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-cog"></i></span>
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu pull-right" role="menu">
                                                {% if vente.statut == 'NON-VA' %}
                                                    <li><a href="{% url 'delete-vente' vente.id %}" onclick="return confirm('Voulez vous réelement supprimer la vente : {{ vente.produit.nomP }} ?')"> <i class="fa fa-trash fa-fw"></i> Supprimer</a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'validate-vente' vente.id %}" onclick="return confirm('Validez la livraison du produit au stock : {{ vente.produit.nomP }} ?')"> <i class="fa fa-check fa-fw"></i> Valider</a>
                                                    </li>
                                                {% else %}
                                                    <p>Aucune action disponible</p>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </td>
                            </tr>

                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                    <p>Aucun enregistrement disponible :-)</p>
                {% endif %}


            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>


{% endblock %}

{% block js %}
<script>
    $(document).ready(function () {
        $('#dataTables-produitvente').DataTable({
            language: {
                url: "{% static 'stock/js/french.json' %}"
            },
            /*"autoWidth": false,
            columns: [
                    { "width": "5%" },
                    { "width": "10%" },
                    { "width": "15%" },
                    { "width": "30%" },
                    {"width": "5%"}
            ],*/
            "columnDefs": [{
                "targets": 4,
                "orderable": false
            }],
        });
    });
</script>
{% endblock %}

stock/templates/produitVente/produitvente_form.html
{% extends '../base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">{{ titre }} - Vente Produit Livré</h2>
    </div>
</div>

{% if messages %}
<div class="container">
        <div class="col-md-4" style="margin-left: 955px">
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{message}}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
</div>
{% endif %}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Formulaire Vente Produit

                <div class="pull-right">
                    <div class="btn-group">
                        <a href="/ventes" class="btn btn-default btn-xs">
                            Liste Ventes Réalisés
                        </a>
                    </div>
                </div>
            </div>
            <form method="post" autocomplete="off" id="ventForm" data-vent1-url="{% url 'ajax_load_qte' %}" data-vent-url="{% url 'ajax_load_tarif' %}" novalidate>
                {% csrf_token %}
                <div class="panel-body">
                        <div class="form-row">
                            <div class="form-group col-md-2">
                                <label class="fw-bolder" style="margin-left:5px" for="codeV">Reference Vente</label>
                                <input class="form-control" required="true" readonly="true"  type="text" id="codeV" name="codeV" value="{{codeV}}" autocomplete="off">
                            </div>
                            <div class="form-group col-md-2">
                                {{ form.dateV|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-2">
                                {{ form.client|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-2">
                                {{ form.remise|as_crispy_field }}
                            </div>
                        </div>
                </div>

                <div class="row" style="margin-right: -95px">
                    <div class="panel-default col-lg-3">
                        <div class="panel-heading card shadow" style="margin-left: 20px; margin-bottom: 10px">

                            <strong style="margin-top: 10px">FORMULAIRE INSERTION VENTE PRODUIT</strong>
                            <br><br>
                            <div class="card-body">
                                <div class="form-group">
                                    <label class="fw-bolder">Produit Stock</label>
                                    {{ form.produit }}
                                </div>
                                <div class="form-group">
                                    <label class="fw-bolder">Tarif Vigueur</label>
                                    {{ form.prix }}
                                </div>
                                <div class="form-group">
                                    <label class="fw-bolder">Quantité Dispo</label>
                                    <span class="form-control" style="margin:auto" id="qteAdderD">{{qte_dis}}</span>
                                </div>
                                <div class="form-group">
                                    <label class="fw-bolder">Quantité</label>
                                    {{ form.qte }}
                                </div>

                                <button class="btn btn-sm btn-warning" id="btn_cancel" type="button">Annuler</button>
                                <button type="button" id="btn_adder" class="btn btn-sm btn-primary" style="margin-left: 5px;"
                                        >Ajouter
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="panel-default col-lg-8">
                        <div class="panel-heading">
                            <strong>LISTE DES PRODUITS - PANIER</strong>

                            <div class="pull-right">
                                    <span style="color:red;font-size:bold;" id="value">

                                    </span>
                            </div>
                            <div class="table-responsive" style="margin-top: 25px">
                                <table class="table table-striped table-bordered table-hover" id="ProduitVente">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Produit</th>
                                        <th>Qte Demandée</th>
                                        <th>Quantité Dispo</th>
                                        <th>Prix</th>
                                        <th>Total</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="text-right">
                        <button type="submit" class="btn btn-sm btn-info">Enregistrer</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function () {
        $('#pdtAdder').select2({

        });
    });

    var btnAdder = document.querySelector('#btn_adder');
    var btnCanceler = document.querySelector('#btn_cancel');

    var pdtAdderField = document.querySelector('#pdtAdder');
    var qteDAdderField = document.querySelector('#qteAdderD');
    var qteAdderField = document.querySelector('#qteAdder');
    var prixAdderField = document.querySelector('#prixAdder');
    var tableLine = document.querySelector('#ProduitVente');
    var tableLineBody = tableLine.querySelector('tbody');
    var index = 0;
    var currentIndex = null;

    var actionUpdate = false;

    function buildLine(line){
        var index = line.dataset.index

        var deleter = line.querySelector('.deleter')
        var editer = line.querySelector('.editer')


        deleter.addEventListener('click', function () {
            var confirmation = confirm('Êtes-vous sûr? Cette action est irréversible!');

            if (confirmation) {
                console.log('deleter click');
                line.remove();
                setTimeout(function () {
                    alert('La ligne a été supprimée.');
                }, 0);
            }
            calculTotal();
        });

        editer.addEventListener('click', function(){
            console.log('editer click')
            var t = line.querySelector('[name="prixIds[]"]');
            var prixId = t ? t.value : null;
            var p = line.querySelector('[name="pdtIds[]"]');
            var pdtId = p ? p.value : null;
            var qteD = line.querySelector('[name="qteD[]"]').value;
            var qte = line.querySelector('[name="qte[]"]').value;

            pdtAdderField.value = pdtId;
            prixAdderField.value = prixId;
            qteDAdderField.textContent = qteD;
            qteAdderField.value = qte;

            btnAdder.innerHTML = 'Modifier';
            actionUpdate = true;

            currentIndex = index;
        });
    }
    $('#btn_cancel').on('click', function() {
        reinit();
    });

    function reinit(){
        currentIndex = null;
        btnAdder.innerHTML = 'Ajouter';
        actionUpdate = false;
        pdtAdderField.value = null;
        qteDAdderField.textContent = null;
        qteAdderField.value = null;
        prixAdderField.value = null;
        var select2Control = $('#pdtAdder');
        select2Control.val(null).trigger('change');
    }

    function calculTotal(){
        var table = document.getElementById("ProduitVente"), sumValTva =0.0, sumVal =0;

        if(table.rows.length >0) {
            for(var i = 1; i < table.rows.length; i++){
                sumVal = sumVal + parseInt(table.rows[i].cells[5].innerHTML);
                sumValTva = sumVal * 1.18
            }
        }
        document.getElementById("value").innerHTML = "TOTAL TTC : "+ sumValTva.toFixed(2) + " F CFA";
    }

    btnAdder.addEventListener('click', function(event){
        var table = document.getElementById("ProduitVente")
        var pdtId = pdtAdderField.value;
        var qteD = qteDAdderField.textContent;
        var qte = qteAdderField.value;
        var prixId = prixAdderField.value;

        if(table.rows.length === 0){
            alert('Svp, Veuillez enregistrer au moins une ligne livraison de produit !');
            reinit();
        }else {
            if(pdtId && qteD && qte && prixId){
                var pdtLibelle = pdtAdderField.options[pdtAdderField.selectedIndex].text;
                var prixLibelle = prixAdderField.options[prixAdderField.selectedIndex].text;
                var currentLine = tableLineBody.querySelector('[data-index="'+ currentIndex +'"]');
                var existedLine = tableLineBody.querySelector('[data-id="'+ pdtId +'"]');
                var totalPrice = parseFloat(qte) * parseFloat(prixLibelle);

                if(existedLine && !actionUpdate){
                    alert('Ce produit est déja dans la liste. Merci de choisir un autre !');
                }else{
                    if (qte<=0 || qte > Number(qteD)){
                        alert('Veuillez saisir une quantité correcte !');
                    }else{
                        if(actionUpdate && currentLine){
                            currentLine.innerHTML = '<td style="text-align:center;">' + currentIndex + '</td><td><input type="hidden" name="pdtIds[]" value="'+ pdtId +'" />'+ pdtLibelle +'</td> <td><input type="hidden" name="qte[]" value="'+ qte +'" />'+ qte +'</td> <td><input type="hidden" name="qteD[]" value="'+ qteD +'" />'+ qteD +'</td> <td><input type="hidden" name="prixIds[]" value="'+ prixId +'" />'+ prixLibelle +'</td> <td>'+ totalPrice +'</td> <td style="text-align:left;"><a class="editer" data-index="'+ currentIndex +'">Modifier</a> <a class="deleter" style="margin-left:5px" data-index="'+ currentIndex +'">Supprimer</a></td>';
                            buildLine(currentLine)
                        }else{
                            if(!currentLine){
                                index++;
                                if(index === 1){
                                    $('#ProduitVente').find('tbody tr').remove();
                                }
                                var newRow = tableLineBody.insertRow(0);
                                newRow.setAttribute('data-index', index);
                                newRow.setAttribute('data-id', pdtId);
                                newRow.innerHTML = '<td style="text-align:center;">' + index + '</td><td><input type="hidden" name="pdtIds[]" value="'+ pdtId +'" />'+ pdtLibelle +'</td> <td><input type="hidden" name="qte[]" value="'+ qte +'" />'+ qte +'</td> <td><input type="hidden" name="qteD[]" value="'+ qteD +'" />'+ qteD +'</td> <td><input type="hidden" name="prixIds[]" value="'+ prixId +'" />'+ prixLibelle +'</td> <td>'+ totalPrice +'</td> <td style="text-align:left;"><a class="editer" data-index="'+ index +'">Modifier</a><a class="deleter" style="margin-left:5px" data-index="'+ index +'">Supprimer</a>  </td>';
                                buildLine(newRow);
                            }
                        }
                    }
                    reinit();
                }
            }
        }
        calculTotal();
    });




</script>
<script>
    $("#pdtAdder").change(function () {
      var url = $("#ventForm").attr("data-vent-url");
      var pId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'pdt_id': pId
        },
        success: function (data) {
          $("#prixAdder").html(data);
        }
      });

    });
</script>
<script>
    $("#prixAdder").change(function () {
      var urlqte = $("#ventForm").attr("data-vent1-url");
      var produitId = $('#pdtAdder').val();

      $.ajax({
        url: urlqte,
        data: {
          'pdt_id': produitId
        },
        success: function (data) {
          $("#qteAdderD").html(data[0]);
        }
      });

    });
</script>
{% endblock %}